window.rd||(window.rd={});window.rd.ip||(window.rd.ip={});rd.ip.scene={};var gl,glCanvas,vertices,shaderProgram,mvMatrix=mat4.create(),mvMatrixStack=[],pMatrix=mat4.create(),cardVertexPositionBuffer,cardVertexTextureCoordBuffer,requestAnimFrameId=0,mouseIsDown=false,mouseMoveTime=new Date,mouseMoveStartX=0,mouseMoveStartY=0,mouseMovePrevX=0,zoom=-15,minZoom=-25,maxZoom=-2.4,inactivityTimerId=0,lastTime=0,isStopped=false,currentlyPressedKeys={};
function initGL(a){try{gl=createWebGLContext(a),gl.viewportWidth=a.width,gl.viewportHeight=a.height}catch(c){}gl||alert("Could not initialise WebGL, sorry :-(")}function createWebGLContext(a,c){for(var b=["webgl","experimental-webgl","webkit-3d","moz-webgl"],e=null,d=0;d<b.length;++d){try{e=a.getContext(b[d],c)}catch(f){}if(e)break}return e}
function getShader(a,c){var b=document.getElementById(c);if(!b)return null;for(var e="",d=b.firstChild;d;)d.nodeType==3&&(e+=d.textContent),d=d.nextSibling;if(b.type=="x-shader/x-fragment")b=a.createShader(a.FRAGMENT_SHADER);else if(b.type=="x-shader/x-vertex")b=a.createShader(a.VERTEX_SHADER);else return null;a.shaderSource(b,e);a.compileShader(b);return!a.getShaderParameter(b,a.COMPILE_STATUS)?(alert(a.getShaderInfoLog(b)),null):b}
function initShaders(){var a=getShader(gl,"shader-fs"),c=getShader(gl,"shader-vs");shaderProgram=gl.createProgram();gl.attachShader(shaderProgram,c);gl.attachShader(shaderProgram,a);gl.linkProgram(shaderProgram);gl.getProgramParameter(shaderProgram,gl.LINK_STATUS)||alert("Could not initialise shaders");gl.useProgram(shaderProgram);shaderProgram.vertexPositionAttribute=gl.getAttribLocation(shaderProgram,"aVertexPosition");gl.enableVertexAttribArray(shaderProgram.vertexPositionAttribute);shaderProgram.textureCoordAttribute=
gl.getAttribLocation(shaderProgram,"aTextureCoord");gl.enableVertexAttribArray(shaderProgram.textureCoordAttribute);shaderProgram.pMatrixUniform=gl.getUniformLocation(shaderProgram,"uPMatrix");shaderProgram.mvMatrixUniform=gl.getUniformLocation(shaderProgram,"uMVMatrix");shaderProgram.samplerUniform=gl.getUniformLocation(shaderProgram,"uSampler");shaderProgram.colorUniform=gl.getUniformLocation(shaderProgram,"uColor")}
function mvPushMatrix(){var a=mat4.create();mat4.set(mvMatrix,a);mvMatrixStack.push(a)}function mvPopMatrix(){if(mvMatrixStack.length==0)throw"Invalid popMatrix!";mvMatrix=mvMatrixStack.pop()}function setMatrixUniforms(){gl.uniformMatrix4fv(shaderProgram.pMatrixUniform,false,pMatrix);gl.uniformMatrix4fv(shaderProgram.mvMatrixUniform,false,mvMatrix)}function degToRad(a){return a*Math.PI/180}function handleWindowClick(){restartInactivityTimer()}
function handleKeyDown(a){currentlyPressedKeys[a.keyCode]=true}function handleKeyUp(a){currentlyPressedKeys[a.keyCode]=false}function handleKeys(){currentlyPressedKeys[33]&&(isStopped=true);currentlyPressedKeys[34]&&(isStopped=false)}function handleMouseDown(){mouseMoveStartY=event.clientY;mouseMovePrevX=event.clientX;mouseMoveTime=new Date;mouseIsDown=true}
function handleMouseUp(){mouseIsDown&&(mouseIsDown=false,moveCards((mouseMovePrevX-event.clientX)/100),Math.abs(mouseMoveStartY-event.clientY)>10&&(zoomDirection=mouseMoveStartY-event.clientY<0?1:-1))}function handleMouseMove(){if(mouseIsDown)moveCards((mouseMovePrevX-event.clientX)/100),speedX=(mouseMovePrevX-event.clientX)/((new Date-mouseMoveTime)*10),mouseMoveTime=new Date,mouseMovePrevX=event.clientX,Math.abs(speedX)>1&&(speedX=speedX>0?1:-1)}
function moveCards(a){for(var c in rd.ip.core.activeCards)if(rd.ip.core.activeCards[c].x-=a,rd.ip.core.activeCards[c].x<0||rd.ip.core.activeCards[c].x>=rd.ip.globals.SCENE_WIDTH)rd.ip.core.activeCards[c].x%=rd.ip.globals.SCENE_WIDTH,rd.ip.core.activeCards[c].x<0&&(rd.ip.core.activeCards[c].x+=rd.ip.globals.SCENE_WIDTH),rd.ip.core.activeCards[c].profile=rd.ip.floatingProfileCard.getNextProfile(zoomDirection)}
function initBuffers(){cardVertexPositionBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,cardVertexPositionBuffer);vertices=[-1,-0.5,0,1,-0.5,0,-1,0.5,0,1,0.5,0];gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.STATIC_DRAW);cardVertexPositionBuffer.itemSize=3;cardVertexPositionBuffer.numItems=4;cardVertexTextureCoordBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,cardVertexTextureCoordBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([0,0,1,0,0,1,1,1]),gl.STATIC_DRAW);
cardVertexTextureCoordBuffer.itemSize=2;cardVertexTextureCoordBuffer.numItems=4}
function drawScene(){gl.viewport(0,0,gl.viewportWidth,gl.viewportHeight);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.enable(gl.BLEND);mat4.perspective(45,gl.viewportWidth/gl.viewportHeight,1,1E3,pMatrix);mat4.identity(mvMatrix);mat4.translate(mvMatrix,[-rd.ip.globals.SCENE_WIDTH/2,-rd.ip.globals.SCENE_HEIGHT/2,0]);for(var a in rd.ip.core.activeCards)rd.ip.core.activeCards[a].draw()}
function animate(){var a=(new Date).getTime();if(lastTime!=0){var c=a-lastTime;mouseIsDown||(moveCards(speedX),Math.abs(speedX)>minSpeedX&&(speedX-=speedX*0.05));if(!mouseIsDown)for(var b in rd.ip.core.activeCards)rd.ip.core.activeCards[b].animate(b,c)}lastTime=a}function tick(){requestAnimFrameId=requestAnimFrame(tick);handleKeys();isStopped||(animate(),drawScene())}
function webGLStart(){if(!glCanvas)glCanvas=document.getElementById("my-canvas"),initGL(glCanvas),initShaders(),initBuffers(),gl.clearColor(0,0,0,0),document.onkeydown=handleKeyDown,document.onkeyup=handleKeyUp}function restartInactivityTimer(){clearTimeout(inactivityTimerId);inactivityTimerId=setTimeout("inactivityTimerTick()",rd.ip.globals.INACTIVITY_INTERVAL*1E3)}
function inactivityTimerTick(){rd.ip.core.profileDetails&&rd.ip.core.profileDetails.hide();rd.ip.core.keyboard&&rd.ip.core.keyboard.hide();rd.ip.core.filter1&&rd.ip.core.filter1.hide();rd.ip.core.filter2&&rd.ip.core.filter2.hide();rd.ip.core.clearFilters()}
function handleClick(){for(var a=1/Math.tan(45*Math.PI/360),c=2/glCanvas.height,b=rd.ip.core.activeCards.length;b--;){var e=rd.ip.core.activeCards[b],d=-e.z/a,f=(event.offsetX-glCanvas.width/2)*c*d+rd.ip.globals.SCENE_WIDTH/2,d=rd.ip.globals.SCENE_HEIGHT/2-(event.offsetY-glCanvas.height/2)*c*d,g=e.x-1,h=e.y-0.5;if(f>g&&f<g+2&&d>h&&d<h+1&&e.z>minZoom+1&&e.z<maxZoom-1){rd.ip.core.profileDetails.show(e.profile);break}}}function startAnimation(){webGLStart();tick()}
function stopAnimation(){requestAnimFrameId=0}var isfirsttime=true;function handleExternalMessages(a){a.data=="play"&&isfirsttime&&(isfirsttime=false,startAnimation())}window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();
window.cancelRequestAnimFrame=function(){return window.cancelAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelRequestAnimationFrame||window.oCancelRequestAnimationFrame||window.msCancelRequestAnimationFrame||clearTimeout}();