window.rd||(window.rd={});window.rd.ip||(window.rd.ip={});rd.ip.core={};
rd.ip.core.init=function(){window.addEventListener("message",handleExternalMessages,false);var a=this;a.profiles=[];a.filteredProfiles=[];a.featuredProfiles=[];a.activeCards=[];a.isAuth=null;a.floatingProfileBgImg=new Image;a.floatingProfileBgImg.src=rd.ip.globals.FLOATING_PROFILE_BG_IMAGE_SRC;a.profileDetails=new rd.ip.ProfileDetails;a.featuredProfileCard=new rd.ip.FeaturedProfileCard;a.filter1=new rd.ip.Filter(rd.ip.globals.ELEMENT_FILTER_BOX_1,rd.ip.globals.ELEMENT_FILTER_LIST_1);a.filter1.onClick=
function(){a.filterProfiles()};a.filter2=new rd.ip.Filter(rd.ip.globals.ELEMENT_FILTER_BOX_2,rd.ip.globals.ELEMENT_FILTER_LIST_2);a.filter2.onClick=function(){a.filterProfiles()};a.keyboard=new rd.ip.Keyboard;a.keyboard.onEnter=function(){a.filterProfiles()};var b=a.getUrlParams();if(_dataUrl_=b.data)_dataUrl_=unescape(_dataUrl_),_dataUrl_=_dataUrl_.replace("_://","://");if(b.refresh)rd.ip.data.refreshInterval=parseInt(b.refresh);a.companyId=b.companyId?b.companyId:"RISEMASTER";a.displayId=b.displayId?
b.displayId:"PREVIEW";a.autoPlay=b.play?b.play=="1"||b.play=="true":false;a.useProxy=rd.ip.globals.USE_IMAGE_PROXY;window.addEventListener("click",handleWindowClick,false);a.checkAuth();this.isAuth&&rd.ip.data.init(rd.ip.core.handleOnDataLoaded)};
rd.ip.core.filterProfiles=function(){this.filteredProfiles=[];for(var a in this.profiles)this.filter1.filterStr&&this.filter1.filterStr!=this.profiles[a].filter1||this.filter2.filterStr&&this.filter2.filterStr!=this.profiles[a].filter2||this.profileMatchesSearchStr(this.profiles[a])&&this.filteredProfiles.push(this.profiles[a]);this.initWorldObjects()};
rd.ip.core.profileMatchesSearchStr=function(a){var b=true;try{if(this.keyboard.searchStr&&rd.ip.globals.SEARCHABLE_COLUMNS&&rd.ip.globals.SEARCHABLE_COLUMNS.length>0){var c="",d;for(d in rd.ip.globals.SEARCHABLE_COLUMNS)c+=" "+a.data[rd.ip.globals.SEARCHABLE_COLUMNS[d]];b=c.toUpperCase().indexOf(this.keyboard.searchStr)!=-1}}catch(e){}return b};
rd.ip.core.clearFilters=function(){this.filter1.clear();this.filter2.clear();this.keyboard.clear();this.filteredProfiles=[];this.filteredProfiles=this.profiles.slice(0);this.initWorldObjects()};rd.ip.core.handleOnDataLoaded=function(a){me=rd.ip.core;me.profiles=a;me.filterProfiles();me.initFilters();me.initWorldObjects();me.featuredProfileCard.restart();parent?parent.postMessage("ready","*"):me.autoPlay&&startAnimation()};
rd.ip.core.initWorldObjects=function(){rd.ip.core.activeCards=[];for(var a in rd.ip.core.filteredProfiles){if(a>rd.ip.globals.MAX_ACTIVE_CARDS)break;var b=new rd.ip.FloatingProfileCard;b.profile=rd.ip.core.filteredProfiles[a];rd.ip.core.activeCards.push(b);rd.ip.core.activeCards.sort(function(a,b){return a.z-b.z})}};
rd.ip.core.initFilters=function(){var a=[],b=[],c;for(c in this.profiles)this.profiles[c].filter1&&(this.arrayHasValue(a,this.profiles[c].filter1)||a.push(this.profiles[c].filter1)),this.profiles[c].filter2&&(this.arrayHasValue(b,this.profiles[c].filter2)||b.push(this.profiles[c].filter2));this.filter1.items=a.sort();this.filter2.items=b.sort()};rd.ip.core.arrayHasValue=function(a,b){for(var c in a)if(a[c]===b)return true;return false};
rd.ip.core.getUrlParams=function(){var a={};try{var b=document.location.search.substr(1).split("&"),c;for(c in b){var d=b[c].split("=");d.length==2&&(a[d[0]]=d[1])}}catch(e){}return a};rd.ip.core.checkAuth=function(){if(this.isAuth===null)this.isAuth=this.callLicensingServer();this.showAuthMessage(!this.isAuth)};
rd.ip.core.showAuthMessage=function(a){var b=document.getElementById("err");if(b&&a!=(b.style.visibility=="visible")&&(b.style.visibility=a?"visible":"hidden",a))b.style.width=window.innerWidth+"px",b.style.height=window.innerHeight+"px",b.style.lineHeight=window.innerHeight+"px",b.innerHTML="Not Authorized"};
rd.ip.core.callLicensingServer=function(){var a=false,b=new XMLHttpRequest;b.onreadystatechange=function(){if(b.readyState==4&&b.status==200){var c=eval("("+b.responseText+")");c&&c.riselicensor&&c.riselicensor.result&&c.riselicensor.result=="yes"&&(a=true)}};b.open("GET","http://riselicensing.appspot.com/api?id=ItemProfiler"+(this.displayId?"&d="+this.displayId:"")+(this.companyId?"&c="+this.companyId:""),false);b.send();return a};